"""Emit every figure in the manuscript as a LaTeX macro, from the run JSON.

Nothing is typed into the draft. If a number changes because an experiment was
rerun, the draft changes when this is rerun and not before.
"""
from __future__ import annotations

import argparse
import json
from collections import Counter
from math import comb
from pathlib import Path

import numpy as np


def load(p):
    p = Path(p)
    return json.loads(p.read_text()) if p.exists() else None


class Macros:
    def __init__(self):
        self.items = {}

    def add(self, name, value, fmt="{:.3f}"):
        if value is None:
            return
        self.items[name] = (fmt.format(value)
                            if isinstance(value, float) else str(value))

    def dump(self, path):
        lines = ["% Generated by src/make_numbers.py. Do not edit.",
                 "% Every number in the manuscript comes from run JSON."]
        for k in sorted(self.items):
            lines.append(f"\\newcommand{{\\{k}}}{{{self.items[k]}}}")
        Path(path).write_text("\n".join(lines) + "\n")
        return len(self.items)


def dark(rows, kind):
    return [r for r in rows if r["model_kind"] == kind and r["cond"] == "dark"]


def sign_p(k, n):
    """Exact two-sided sign-test p for k of n seeds falling one way."""
    k = max(k, n - k)
    tail = sum(comb(n, i) for i in range(k, n + 1))
    return min(1.0, 2 * tail / 2 ** n)


def plane_stats(rows, j):
    """Per-plane summary.

    `beats` counts seeds below the median of their own matched null, which is
    the headline comparison. `strict` counts seeds below that null's *minimum*,
    which is what separates a plane that clears every matched direction from
    one that merely clears half of them. The two agree for a coordinate the
    dynamics use and diverge sharply for one they do not, so reporting only
    the first would overstate a weak plane.
    """
    beats = sum(1 for r in rows if r["planes"][j]["residual"]
                < r["planes"][j]["null_residual_median"])
    return {
        "residual": float(np.mean([r["planes"][j]["residual"] for r in rows])),
        "null": float(np.mean([r["planes"][j]["null_residual_median"]
                               for r in rows])),
        "beats": beats,
        "strict": sum(1 for r in rows if r["planes"][j]["residual"]
                      < r["planes"][j]["null_residual_min"]),
        "gap": float(np.mean([r["planes"][j]["null_residual_median"]
                              - r["planes"][j]["residual"] for r in rows])),
        "p": sign_p(beats, len(rows)),
        "n": len(rows),
        "kappa": float(np.mean([r["planes"][j]["best_kappa"] for r in rows])),
        "votes": Counter(tuple(r["planes"][j]["best_basis"]) for r in rows),
    }


def basis_kappa(rows, j, basis):
    vals = []
    for r in rows:
        for b in r["planes"][j]["bases"]:
            if tuple(b["basis"]) == basis:
                vals.append(b["kappa"])
    return float(np.mean(vals)) if vals else None


def _domain_para(dmc):
    rows = dmc["rows"]
    n = len(rows)
    out = ("\\paragraph{Domain.} We apply the criterion to a world model "
           "trained from pixels on \\texttt{reacher} from the control suite "
           "\\citep{tassa2018dmc} under random-policy interaction. Its two "
           "actuated hinges differ in exactly the way the criterion cares "
           "about: the shoulder is unlimited and turns through more than two "
           "full revolutions, while the wrist is limited to $\\pm 2.793$ "
           "radians. One benchmark, one model, both families. ")
    for j, name in enumerate(("shoulder", "wrist")):
        fam = Counter(r["joints"][j]["family"] for r in rows)
        win, cnt = fam.most_common(1)[0]
        rot = np.mean([r["joints"][j]["rotation"]["residual"] for r in rows])
        tra = np.mean([r["joints"][j]["translation"]["residual"]
                       for r in rows])
        out += (f"The {name} is read as {win} in {cnt} of {n} seeds "
                f"(rotation residual {rot:.3f}, translation {tra:.3f}). ")
    return out


def _generality_sentence(arch_ok, domain_ok):
    """The abstract's closing sentence, assembled from what is on disk.

    The abstract is prose and prose is where an overclaim survives longest: the
    body paragraphs are already gated on their JSON, but a typed abstract kept
    asserting an architecture and a domain result while both were still running.
    Generating it means the claim cannot outrun the evidence.
    """
    clauses = ["generalises past rotations to bounded joints"]
    if arch_ok:
        clauses.append("agrees across a convolutional GRU and a stochastic "
                       "latent-variable world model")
    if domain_ok:
        clauses.append("reads a standard control-suite domain")
    if len(clauses) == 1:
        body = clauses[0]
    elif len(clauses) == 2:
        body = clauses[0] + ", and " + clauses[1]
    else:
        body = clauses[0] + ", " + clauses[1] + ", and " + clauses[2]
    return "The test " + body + "."


def _horizon_para(data, expected_seeds=8, kind="gru"):
    """Is the dissociation an artifact of the comparison horizon?

    An earlier calibration on the v2 environment appeared to show joint 2's
    concentration climbing with the horizon. It does not survive the move to
    the environment this manuscript reports: on v3 under the same search mode
    it is non-monotone across seeds. What is stable is the dissociation
    itself, so that is what this reports, per horizon, and only for horizons
    where every seed has landed.

    Restricted to one architecture, because only the convolutional GRU
    checkpoints cleared the blackout validity gate. The sweep also covers the
    modular model; averaging the two would fold an ungated architecture into a
    reported number, which is the thing the gate exists to prevent.
    """
    if not data:
        return ""
    rows = [r for r in data["rows"]
            if not r["untrained"] and r["model_kind"] == kind]
    if not rows:
        return ""
    parts, done = [], []
    for h in sorted({r["horizon"] for r in rows}):
        at_h = [r for r in rows if r["horizon"] == h]
        # Do not report a horizon until every seed has landed, or the sentence
        # would describe a different n each time it is regenerated.
        if len(at_h) < expected_seeds:
            continue
        r1 = float(np.mean([r["planes"][0]["residual"] for r in at_h]))
        n1 = float(np.mean([r["planes"][0]["null_residual_median"]
                            for r in at_h]))
        r2 = float(np.mean([r["planes"][1]["residual"] for r in at_h]))
        n2 = float(np.mean([r["planes"][1]["null_residual_median"]
                            for r in at_h]))
        parts.append((h, r1, n1, r2, n2))
        done.append(h)
    if not parts:
        return ""
    # List the horizons actually reported, not every horizon the sweep touched:
    # a partially finished horizon would otherwise be named in the sentence
    # while contributing nothing to the numbers behind it.
    prox = ", ".join(f"{p[1]:.2f}" for p in parts)
    dist = ", ".join(f"{p[3]:.2f}" for p in parts)
    lo = min(min(p[2], p[4]) for p in parts)
    # A sentence rather than a paragraph: this is the same kind of claim as the
    # null-draw check it sits beside, and at four pages a second heading for it
    # costs more than it earns.
    return (" The separation also holds across comparison horizons. At "
            + ", ".join(str(h) for h in done)
            + f" steps the proximal residual is {prox} and the distal is "
            f"{dist}, against nulls never below {lo:.2f}, on "
            f"{expected_seeds} seeds at each horizon.")


def _null_stability(m, search, horizon, kind="gru", h=4):
    """How reproducible is the null the criterion is judged against?

    The horizon sweep re-runs the same configuration as the main search: same
    variant, mode, batch and null count. Discovery is deterministic and the
    residuals come back bit-identical, but the null is *sampled*, so its median
    does not. That gives two independent null draws against one set of
    residuals, which is the only honest way we have to ask whether a seed count
    like "7 of 8" is a property of the model or of the draw.

    It is not the same for both joints, and the difference is the point: the
    proximal margin is an order of magnitude larger than the null's own drift,
    while the distal margin is a small multiple of it and its seed count moves
    between draws. Reporting a single p-value for the distal joint would state
    one draw's answer as if it were stable.
    """
    if not (search and horizon):
        return
    a = {r["seed"]: r for r in dark(search["rows"], kind)}
    b = {r["seed"]: r for r in horizon["rows"]
         if r["model_kind"] == kind and r["horizon"] == h and not r["untrained"]}
    seeds = sorted(set(a) & set(b))
    if len(seeds) < 2:
        return
    m.add("nNullDraws", 2, "{}")
    m.add("nNullSeeds", len(seeds), "{}")
    for j, jt in ((0, "One"), (1, "Two")):
        margins, beats, drift = [], [], []
        for src in (a, b):
            mg = [src[s]["planes"][j]["null_residual_median"]
                  - src[s]["planes"][j]["residual"] for s in seeds]
            margins.append(float(np.mean(mg)))
            beats.append(sum(1 for x in mg if x > 0))
        drift = float(np.mean([
            abs(a[s]["planes"][j]["null_residual_median"]
                - b[s]["planes"][j]["null_residual_median"]) for s in seeds]))
        m.add(f"Serial{kind.title()[:3]}P{jt}MarginA", margins[0])
        m.add(f"Serial{kind.title()[:3]}P{jt}MarginB", margins[1])
        m.add(f"Serial{kind.title()[:3]}P{jt}BeatsA", beats[0], "{}")
        m.add(f"Serial{kind.title()[:3]}P{jt}BeatsB", beats[1], "{}")
        m.add(f"Serial{kind.title()[:3]}P{jt}NullDrift", drift)
        m.add(f"Serial{kind.title()[:3]}P{jt}MarginOverDrift",
              float(np.mean(margins)) / drift if drift else None, "{:.0f}")


def _validity_para(passed, rejected):
    """The gate every reported checkpoint had to clear, and what it rejected.

    Reported rather than assumed, because the checkpoints this gate rejects
    trained to an ordinary-looking reconstruction loss and failed only here.
    """
    if not passed and not rejected:
        return ""
    out = ("\\paragraph{Validity.} Every checkpoint had to beat frame "
           "persistence on blacked-out steps before any family was fitted. A "
           "model that cannot predict during a blackout carries no prior for "
           "the criterion to read. ")
    if passed:
        bits = [f"{lab} {v['n_beating_persistence']} of {v['n_models']} "
                f"(median ratio {v['median_ratio']:.2f})" for lab, v in passed]
        out += ("All models reported above clear the gate: " +
                "; ".join(bits) + ", where a ratio below $1$ beats holding "
                "the last visible frame. ")
    if rejected:
        ratios = ", ".join(f"{v['median_ratio']:.2f}" for _, v in rejected[:-1])
        ratios += f" and {rejected[-1][1]['median_ratio']:.2f}"
        names = ", ".join(lab for lab, _ in rejected[:-1])
        names += f" and {rejected[-1][0]}"
        out += ("A stochastic latent-variable world model trained on the same "
                "data under the same budget fails on every seed of "
                f"every setting we tried (median ratios {ratios} on {names}), "
                "reaching an ordinary reconstruction loss while predicting a "
                "blackout worse than persistence. We therefore report no "
                "architecture or domain generalisation. An earlier sweep "
                "failed differently, through a free-nats floor above the "
                "model's operating KL that removed the KL gradient, and no "
                "training-loss statistic separated either failure from a "
                "sound run. That defect was fixed before these runs. The "
                "gate constrains these checkpoints at this budget, not the "
                "architecture class.")
    return out


def main(runs, output):
    runs, m = Path(runs), Macros()

    # -- what each environment shows -------------------------------------
    env = load(runs / "arm_env_diagnostic_all.json")
    if env:
        for key, tag in (("v2", "Serial"), ("v4", "Parity"), ("v5", "Decoup")):
            b = env.get(key)
            if not b:
                continue
            d, s = b["linear_decodability"], b["sensitivity"]
            m.add(f"env{tag}RatioOne", s["ratio_joint1_over_joint2"], "{:.2f}")
            m.add(f"env{tag}DecOne", d["q1"]["held_out_concentration"])
            m.add(f"env{tag}DecTwo", d["q2"]["held_out_concentration"])
            m.add(f"env{tag}DecSum",
                  d["q1_plus_q2"]["held_out_concentration"])

    # -- the three environments, conjugacy -------------------------------
    for tag, fname in (("Serial", "arm_torus_search.json"),
                       ("Parity", "arm_torus_search_v4.json"),
                       ("Decoup", "arm_torus_search_v6.json")):
        data = load(runs / fname)
        if not data:
            continue
        for kind, kt in (("gru", "Gru"), ("modular", "Mod")):
            rows = dark(data["rows"], kind)
            if not rows:
                continue
            m.add(f"n{tag}Seeds", len(rows), "{}")
            for j, jt in ((0, "One"), (1, "Two")):
                st = plane_stats(rows, j)
                m.add(f"{tag}{kt}P{jt}Resid", st["residual"])
                m.add(f"{tag}{kt}P{jt}Null", st["null"])
                m.add(f"{tag}{kt}P{jt}Kappa", st["kappa"])
                m.add(f"{tag}{kt}P{jt}Beats", st["beats"], "{}")
                m.add(f"{tag}{kt}P{jt}Strict", st["strict"], "{}")
                m.add(f"{tag}{kt}P{jt}Gap", st["gap"])
                m.add(f"{tag}{kt}P{jt}P", st["p"], "{:.4f}")
                top, cnt = st["votes"].most_common(1)[0]
                m.add(f"{tag}{kt}P{jt}Basis",
                      "(" + ",".join(str(x) for x in top) + ")", "{}")
                m.add(f"{tag}{kt}P{jt}Votes", cnt, "{}")
            for j, jt in ((0, "One"), (1, "Two")):
                for basis, bt in (((1, 0), "Prox"), ((0, 1), "Dist"),
                                  ((1, 1), "Sum")):
                    m.add(f"{tag}{kt}P{jt}K{bt}", basis_kappa(rows, j, basis))

    # -- group family, per architecture ----------------------------------
    for tag, fname in (("FamParityGru", "arm_family_v4.json"),
                       ("FamBoundGru", "arm_family_v7.json"),
                       ("FamWrapRssm", "rssm_family_v6.json"),
                       ("FamBoundRssm", "rssm_family_v7.json")):
        data = load(runs / fname)
        if not data:
            continue
        rows = data["rows"]
        m.add(f"n{tag}Seeds", len(rows), "{}")
        for j, jt in ((0, "One"), (1, "Two")):
            fams = Counter(r["joints"][j]["family"] for r in rows)
            win, cnt = fams.most_common(1)[0]
            m.add(f"{tag}P{jt}Family", win, "{}")
            m.add(f"{tag}P{jt}FamilyN", cnt, "{}")
            m.add(f"{tag}P{jt}Rot",
                  float(np.mean([r["joints"][j]["rotation"]["residual"]
                                 for r in rows])))
            m.add(f"{tag}P{jt}Tra",
                  float(np.mean([r["joints"][j]["translation"]["residual"]
                                 for r in rows])))

    # -- prose that must not exist without its evidence -------------------
    # A paragraph asserting a result is emitted only when the JSON backing it
    # is on disk. If an experiment has not finished, the claim is absent from
    # the paper rather than present and unsupported.
    wrap = load(runs / "rssm_family_v6.json")
    bound = load(runs / "rssm_family_v7.json")
    arch = ""
    if wrap:
        n = len(wrap["rows"])
        fam = Counter(r["joints"][0]["family"] for r in wrap["rows"])
        win, cnt = fam.most_common(1)[0]
        rot = np.mean([r["joints"][0]["rotation"]["residual"]
                       for r in wrap["rows"]])
        tra = np.mean([r["joints"][0]["translation"]["residual"]
                       for r in wrap["rows"]])
        arch = (
            "\\paragraph{Architecture.} Everything above uses a convolutional "
            "GRU. We repeat the family check on a recurrent state-space model, "
            "which carries a stochastic latent with a prior conditioned on the "
            "action and a posterior that also sees the observation. Its "
            "withheld-observation window \\emph{is} the prior path, so nothing "
            "has to be added to probe it. On the wrapping environment it "
            f"returns {win} in {cnt} of {n} seeds "
            f"(residual {rot:.3f} against {tra:.3f} for the other family)")
        if bound:
            nb = len(bound["rows"])
            fb = Counter(r["joints"][0]["family"] for r in bound["rows"])
            wb, cb = fb.most_common(1)[0]
            rb = np.mean([r["joints"][0]["rotation"]["residual"]
                          for r in bound["rows"]])
            tb = np.mean([r["joints"][0]["translation"]["residual"]
                          for r in bound["rows"]])
            arch += (f", and with joint stops added it returns {wb} in "
                     f"{cb} of {nb} "
                     f"(residual {tb:.3f} against {rb:.3f}). The verdicts match "
                     "the convolutional model's on both environments.")
        else:
            arch += ". The bounded counterpart is not yet available."
    m.items["ARCHPARA"] = arch

    dmc = load(runs / "dmc_family_reacher.json")
    m.items["DOMAINPARA"] = "" if not dmc else _domain_para(dmc)
    m.items["GENERALITYSENT"] = _generality_sentence(bool(wrap and bound),
                                                     bool(dmc))

    # The figure caption may only claim the axes the figure actually shows.
    span = []
    if wrap and bound:
        span.append("by swapping a convolutional GRU for a stochastic "
                    "latent-variable model")
    if dmc:
        span.append("by moving to a physics engine")
    m.items["FIGCAPSPAN"] = (
        "The verdict is unchanged " + " or ".join(span) + "." if span else "")

    # Contribution (iv) and the scope sentence in the limitations both name
    # axes that only exist if their runs landed.
    axes = ["group family"]
    if wrap and bound:
        axes.append("architecture")
    if dmc:
        axes.append("domain")
    m.items["CONTRIBFOUR"] = (
        "generality checks across " +
        (", ".join(axes[:-1]) + " and " + axes[-1] if len(axes) > 1
         else axes[0]) + ".")
    m.items["LIMSCOPE"] = (
        "The environments are small and synthetic apart from the "
        "control-suite domain." if dmc else
        "Every environment is small and synthetic.")

    passed, rejected = [], []
    for label, fname in (("wrapping joints,", "gru_validity_v6.json"),
                         ("bounded joints,", "gru_validity_v7.json")):
        v = load(runs / fname)
        if v and v.get("n_models"):
            (passed if v["verdict"] == "PASS" else rejected).append((label, v))
    for label, fname in (("the wrapping arm", "rssm_validity_v6.json"),
                         ("the bounded arm", "rssm_validity_v7.json"),
                         ("control-suite reacher", "dmc_validity_reacher.json")):
        v = load(runs / fname)
        if v and v.get("n_models"):
            (passed if v["verdict"] == "PASS" else rejected).append((label, v))
    m.items["VALIDITYPARA"] = _validity_para(passed, rejected)

    # -- untrained response floor -----------------------------------------
    # Concentration is bounded below by what an untrained network of the same
    # shape returns, so a decodability claim is only meaningful against it.
    untr = load(runs / "arm_torus_untrained.json")
    if untr:
        for kind, kt in (("gru", "Gru"), ("modular", "Mod")):
            rows = dark(untr["rows"], kind)
            if not rows:
                continue
            m.add(f"nUntr{kt}Seeds", len(rows), "{}")
            for j, jt in ((0, "One"), (1, "Two")):
                ks = [r["planes"][j]["best_kappa"] for r in rows]
                m.add(f"Untr{kt}P{jt}Kappa", float(np.mean(ks)))
                m.add(f"Untr{kt}P{jt}KappaMax", float(np.max(ks)))
                m.add(f"Untr{kt}P{jt}Resid",
                      float(np.mean([r["planes"][j]["residual"]
                                     for r in rows])))

    # -- how reproducible is the null itself? -----------------------------
    _null_stability(m, load(runs / "arm_torus_search.json"),
                    load(runs / "arm_torus_horizon_v3.json"))

    # -- comparison-horizon robustness ------------------------------------
    # The dissociation must not be an artifact of the window the criterion
    # compares over. Emitted only for horizons actually on disk, and only
    # once every seed at that horizon has finished, so a partial sweep
    # cannot silently narrow the claim.
    m.items["HORIZONPARA"] = _horizon_para(load(runs /
                                                "arm_torus_horizon_v3.json"))

    # -- the exact test's floor at eight pairs ----------------------------
    m.add("exactFloor", 0.0078125, "{:.7f}")
    m.dump(output)
    print(output, len(m.items), "macros")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", default="runs")
    ap.add_argument("--output", default="paper/numbers.tex")
    a = ap.parse_args()
    main(a.runs, a.output)
